/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define _GLFW_BUILD_DLL

#undef _GLFW_COCOA

#undef _GLFW_OSMESA

#undef _GLFW_USE_HYBRID_HPG

#undef _GLFW_VULKAN_STATIC

#undef _GLFW_WAYLAND

#undef _GLFW_WIN32

#define _GLFW_X11

